# Generated by Django 3.2.18 on 2023-03-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_field_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='keterangan',
            field=models.CharField(choices=[('', 'Pilih keterangan'), ('Selesai', 'Selesai'), ('Mendatang', 'Mendatang')], default='Mendatang', max_length=50),
        ),
    ]
