# Generated by Django 3.2.18 on 2023-03-30 17:27

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_add_field_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='dana',
            name='bukti',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=50, scale=0.5, size=[1920, 1080], upload_to='whatever'),
        ),
        migrations.AlterField(
            model_name='event',
            name='foto_sebelum',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=50, scale=0.5, size=[1920, 1080], upload_to='whatever'),
        ),
        migrations.AlterField(
            model_name='event',
            name='foto_setelah',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=50, scale=0.5, size=[1920, 1080], upload_to='whatever'),
        ),
        migrations.AlterField(
            model_name='event',
            name='keterangan',
            field=models.CharField(choices=[('Selesai', 'Selesai'), ('Mendatang', 'Mendatang')], default='Mendatang', max_length=50),
        ),
    ]
