# Generated by Django 3.2.18 on 2023-03-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_add_field_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('nama', models.CharField(max_length=50)),
                ('daerah', models.CharField(max_length=50)),
                ('komentar', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
