# Generated by Django 3.2.18 on 2023-03-31 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_add_komentar_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
            preserve_default=False,
        ),
    ]
