# Generated by Django 3.2.18 on 2023-03-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_add_model_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date and Time')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time')),
                ('nama', models.CharField(max_length=250)),
                ('posisi', models.CharField(max_length=50)),
                ('linkedin', models.URLField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
