# Generated by Django 3.2.18 on 2023-06-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_add_foto_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tim',
            options={'ordering': ('display_order',)},
        ),
        migrations.AddField(
            model_name='tim',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
